version: '3.8'
services:
  webserver:
    build: ./docker/general
    container_name: ubuntu.${APP_NAMESPACE:-johncms}
    depends_on:
      - mariadb
    volumes:
      - .:/var/www/html
    ports:
      - '${NGINX_HTTP_PORT:-}:80'
      - '${NGINX_HTTP_PORT:-}:443'
    networks:
      - web
      - default
    labels:
      - traefik.enable=true
      - traefik.http.routers.web-http-${APP_NAMESPACE:-johncms}.rule=Host(`${APP_HOST:-johncms.loc}`)
      - traefik.http.routers.web-https-${APP_NAMESPACE:-johncms}.rule=Host(`${APP_HOST:-johncms.loc}`)
      - traefik.http.routers.web-https.tls=true
  mariadb:
    image: 'mariadb:10'
    container_name: mariadb.${APP_NAMESPACE:-johncms}
    ports:
      - '${FORWARD_DB_PORT:-}:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD:-johncms}'
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: '${DB_DATABASE:-johncms}'
      MYSQL_USER: '${DB_USERNAME:-johncms}'
      MYSQL_PASSWORD: '${DB_PASSWORD:-password}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - './docker/mariadb/data:/var/lib/mysql'
    networks:
      - web
      - default
    labels:
      - traefik.enable=false

networks:
  web:
    name: traefik_default
    external: true
