controllers:
  resource:
    path: ../src
    namespace: App
  type: attribute
  prefix: '/api'

spa:
  controller: App\Application\Controller\Shared\SpaController::index
  path: '/{page}'
  requirements:
    page: '^(?!api).*'
